### ISSUE TITLE
Use Box instead of Vec for RAM and PIF ROM data

### ISSUE THREAD

**Issue by ketsuban** [yupferris/rustendo64#27]
You tried this in one of the first episodes but fell down because `Box::new` allocates on the stack and then moves into the heap. While box syntax will solve this for good, you can also slightly alter your Cargo debug profile and the call to `Box::new` will be inlined.

``` toml
[profile.dev]
opt-level = 1
```

**Comment by yupferris** [comment]
Thanks for the tip! I didn't realize you could tweak the build profiles like this, that's good to know.

I kinda feel like this is a bit of a janky solution though? It's kind of a roundabout way to solve the problem, and if a more proper solution is on the way and for now we can use something that's more explicit (`Vec`) I think we've already made the best choice.

**Comment by emoon** [comment]
What you can do instead

``` Rust
vec![u8; size].into_boxed_slice();
```

If I remember correct.

https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.into_boxed_slice

**Comment by ketsuban** [comment]
I agree that box syntax is the proper solution, but I also think `Vec` is the wrong tool for the job here because `Vec` is designed to be capable of expanding, which isn't suitable for RAM where the size is already fully known at compile-time.

@emoon: That returns a `Box<[u8]>`, which can't be indexed since the inner `[u8]` is unsized. Converting that to a `Box<[u8; COMPILE_TIME_CONSTANT]>` is ugly.

``` rust
let memory = {
    let mem_ptr = Box::into_raw(vec![0u8; MEM_SIZE].into_boxed_slice()) as *mut [u8; MEM_SIZE];
    unsafe { Box::from_raw(mem_ptr) }
};
```

**Comment by Ryman** [comment]
Another alternative is to newtype around a `Vec` to limit the interface to `&[T]` / `&mut [T]` using `Deref` traits, e.g. from a simple interpreter: [RAM](https://github.com/Ryman/hack_simulator/blob/master/interpreter/src/memory/ram.rs), [ROM](https://github.com/Ryman/hack_simulator/blob/master/interpreter/src/memory/rom.rs#L57-L65)

**Comment by birkenfeld** [comment]
> @emoon: That returns a Box<[u8]>, which can't be indexed since the inner [u8] is unsized. Converting that to a Box<[u8; COMPILE_TIME_CONSTANT]> is ugly.

Being unsized has nothing to do with indexing; you can definitely index slices. Bounds checking is done at runtime anyway.

So I would also vote for `into_boxed_slice()`, it is the cleanest solution until box syntax is stabilized.

**Comment by ketsuban** [comment]
Huh. Okay then. I thought I'd tested that before and had using a boxed slice not index.

**Comment by yupferris** [comment]
I remember `into_boxed_slice` being suggested before, and I think that's our best option currently.

**Comment by simias** [comment]
Note that I've had issues with using boxed arrays insteard of `Vec`. For my PSX emulator I needed a 1MB VRAM buffer and I attempted to replace the Vec<u16> with a box<[u16; 1024 \* 512]> but it stack overflowed on Windows because apparently rustc refused to optimize `let buffer = Box:new([0; 1024 * 512])` without using a stack temporary. Windows has a 1MB stack by default so that crashed (although I didn't notice the problem for a long while because linux uses a 8MB stack by default...). I've had the same behavior with `Rc::new`.

Anyway, not being able to easily tell rustc how I want my stuff allocated has been my major annoyance with Rustation so far, if you're developping on Linux and want to make sure your code works on windows I suggest running you code with `limit stacksize 1M` if you want to catch those rustc treacheries.

In C I'd just alloc all of my context at once in one big malloc in `main` and initialize it incrementally later on but I can't do that in Rust unless I use `unsafe`.

Note that this is not just a pointless nitpick, I've been hacking Mednafen's PlayStation emulator lately and changing this VRAM buffer from a "static" class member to a pointer to heap memory resulted in significantly worse performance because of the added pointer indirection. This is all very annoying... I hope "placement new" will help with this somehow.

**Comment by emoon** [comment]
Hum?

When I do

``` Rust
fn main() {
    let mut temp = vec![0; 1024 * 1024].into_boxed_slice();
    ...
}
```

I get

``` Assemly
    .cfi_offset %rbp, -16
    movl    $4194304, %edi
    movl    $4, %esi
    callq   __rust_allocate@PLT
    movq    %rax, %r15
    testq   %r15, %r15
    je  .LBB0_1
    xorl    %ebx, %ebx
    xorl    %esi, %esi
    movl    $4194304, %edx
    movq    %r15, %rdi
    callq   memset@PLT
```

This is a heap allocation + a memset which is what I expect to see.

**Comment by yupferris** [comment]
I think the issues @simias is referring to only apply _without_ the `into_boxed_slice` fix, is that correct? (the bugs he describes are exactly why I used a `Vec` instead in the first place; I ran into them in [snes-apu](https://github.com/emu-rs/snes-apu) as well)

**Comment by yupferris** [comment]
(also really good to see you here @simias; your psx emu/writeup was one of the primary motivators for starting this project!)

**Comment by emoon** [comment]
Ah yeah, that might go on the stack and be a problem yes. `into_boxed_slice` seems to do what one wants to use here.

**Comment by simias** [comment]
Yeah I didn't attempt to use the `into_boxed_slice`, it might have been the solution to my problem (although it's a bit silly that a simple Box::new() doesn't seem to optimize properly).

Note that there's still the issue of adding a pointer indirection but I suppose at that point it would be a premature optimization.

**Comment by yupferris** [comment]
Yeah, what we really need is the `box` syntax, but until we get that, `into_boxed_slice` looks like our best option so far.

**Comment by emoon** [comment]
Agreed. I really hope `box` will become stable soon.

**Comment by simias** [comment]
@yupferris glad to hear that it was helpful, I'll watch your videos, it looks very interesting. I'll have to continue my doc on the PlayStation at some point...

**Comment by yupferris** [comment]
@simias Hope you like watching the videos, and I hope you continue to work on your writeup! I really liked the format, and it was extra motivating to see someone doing an emulator in rust for sufficiently ambitious hardware. I think that was the tipping point for me to dive into this one :)

**Comment by simias** [comment]
FYI I ended up using @Ketsuban's method to allocate an array on the heap using `Vec::into_boxed_slice` and an unsafe cast.

In order not to have unsafe code all over my codebase I put it in a `box_array` macro: https://github.com/simias/rustation/blob/master/src/box_array.rs

This way I can do:

``` rust
struct Ram {
    data: Box<[u8; RAM_SIZE]>
}

impl Ram {
    pub fn new() -> Ram {

        Ram { data: box_array![0xca; RAM_SIZE] }
    }
}
```

I see that you ended up using `[u8]` slices yourself which is of course perfectly valid but I thought it was annoying to lose the static length information.

**Comment by yupferris** [comment]
Ah yeah, this is nice, thanks for sharing! I think I'll stick with the `[u8]`'s for now as I don't think there's much to be _gained_ in this case (since we don't have dependent types and we're still gonna do bounds checks out the ass), although I admit the more "proper" types do feel a bit better :)
